#!/bash

# the core lib provides functions that must be omnipresent
# it provides 'require' itself so so it must be sourced.

# the std lib is initially sourced to bootstrap it
declare -gA BAR_REQUIRE_LOADED=(["core_lib"]=true)

function require
{
    trace "$*"
    declare -i rc=0
    local mod
    #shellcheck disable=2167,2165
    for mod in "$@"; do
        for mod in "$BARF_DIR/"$mod; do
            local modname="${mod##*/}"
            if [[ ! -v BAR_REQUIRE_LOADED["$modname"] ]]; then
                if [[ -f "$mod" ]]; then
                    trace "loading: $mod"
                    BAR_REQUIRE_LOADED["$modname"]=pending
                    # shellcheck disable=SC1090 # dynamic source
                    source "$mod" && BAR_REQUIRE_LOADED["$modname"]=true
                else
                    BAR_REQUIRE_LOADED["$modname"]=false
                    rc=1
                fi
            fi
        done
    done
    return $rc
}


function source_info # [N] - returns file:line N (or 0) up the bash call stack
{
    echo "${BASH_SOURCE[$((${1:-0}+1))]}:${BASH_LINENO[$((${1:-0}))]}:${FUNCNAME[$((${1:-0}+1))]:+${FUNCNAME[$((${1:-0}+1))]}:}"
}

function DBG ## [message..] - for print-style debugging, should not be present in production code
{
    echo -e "\033[1;37;41m  DBG:\033[0m $(source_info 1) $*" >&2
}

function die ## [message..] - prints 'message' to stderr and exits with failure
{
    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 0 ]]; then
        echo -e "\033[1;91mPANIC:\033[0m $(source_info 1) $*" >&2
    fi
    exit 1
}

function trace ## [message] - may prints a trace message to stderr
{
    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 5 ]]; then
        echo -e "\033[1;96mTRACE:\033[0m $(source_info 1) $*" >&2
    fi
}

function error ## [message..] - may print a error message to stderr and return failure
{
    # TODO: (( ))
    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 0 ]]; then
        echo -e "\033[1;31mERROR:\033[0m $(source_info 1) $*" >&2
    fi
}

function warn ## [message..] - may print an warning to stderr
{
    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 1 ]]; then
        echo -e "\033[1;35m WARN:\033[0m $*" >&2
    fi
}

function note ## [message..] - may print an important notice to stderr
{
    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 1 ]]; then
        echo -e "\033[1;35m NOTE:\033[0m $*" >&2
    fi
}

function info ## [message..] - may print an informal message to stderr
{
    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 3 ]]; then
        echo -e "\033[1;34m INFO:\033[0m $*" >&2
    fi
}

function debug ## [message..] - may print a debug message to stderr
{
    if [[ "${BAR_VERBOSITY_LEVEL:-5}" -gt 4 ]]; then
        echo -e "\033[1;36mDEBUG:\033[0m $(source_info 1) $*" >&2
    fi
}

