#!/bash

function githook_enable
{
     local hook
     # shellcheck disable=SC2155
     local bar="$(git_bar)"
     bar="${bar##*/}"
     for hook in "$@"; do
         info "enabling hook: $hook"
          ln -s "../../$bar" "$(git_dir)/hooks/$hook" || {
              error "installing hook $hook failed"
              return 1
          }
     done
}

rule githook_enable: is_git_toplevel -

function githook_disable
{
    local hook
     for hook in "$@"; do
         info "disabling hook $hook"

         # shellcheck disable=SC2155
         local hook_link="$(readlink -f "$(git_dir)/hooks/$hook")" 
         if [[ "$hook_link" = "$(git_bar)" ]]; then
                rm "$(git_dir)/hooks/$hook"
                debug "removed hook $hook"
            else
                error "$hook: not a hook under bar control"
                return 1
         fi
     done
}

rule githook_disable: is_git_toplevel -
