#!/bash

# library of general functions

# checks whenever a shell command is in PATH
function is_command_installed
{
    if command -v "$1" >/dev/null; then
        return 0
    else
        info "$1 not installed"
        return 1
    fi
}
memofn is_command_installed

# checks whenever 'bar' is called by a name matching a pattern (eg. git hook symlinks)
function called_as ## [pattern..]
{
    local pat
    for pat in "$@"; do
        # shellcheck disable=SC2053
        [[ "$BASH_ARGV0" = $pat ]] && {
            debug "called as $BASH_ARGV0 matched $pat"
            return 0
        }
    done
    trace "$BASH_ARGV0 not matched"
    return 1
}

