#!/bash
#shellcheck disable=SC2016

# This is the barfile for maintaining 'bar' itself. A more generalized and customizeable barfile
# that become installed with 'bar init_local' is the Barf.default file in this directory.

# We only lint here
rule main: lint doc

# manually testing the staged changes
rule test_staged: testdir_enter lint

# maintenance rules
rule build_docs: -- './bar help >README'

# TODO: check that doc is up to date when committing
#rule test_doc: -- 'git diff --exit-code README'

# called as *bar run the 'main' rule in the current dir
rule 'called_as? *bar' main

# called by another name (githook), create temporary testdir and run the main rule there
rule '!called_as *bar' testdir_enter main
#rule 'called_as? *.git/hooks/*'

# for debugging
rule --debug: -- '
     BAR_VERBOSITY_LEVEL=5
     rule_eval "${RULE_ARGS[@]:-MAIN}"
'

rule --trace: -- '
     BAR_VERBOSITY_LEVEL=6
     rule_eval "${RULE_ARGS[@]:-MAIN}"
'

rule --verbose: -- '
     BAR_VERBOSITY_LEVEL+=1
     rule_eval "${RULE_ARGS[@]:-MAIN}"
'
