#!/bash

## git cliff changelog generation

export GIT_CLIFF_OUTPUT="${GIT_CLIFF_OUTPUT:-CHANGELOG.md}"

function cliff_changelog
{
    git cliff
    [[ -f "cliff.toml" ]] && git add "cliff.toml"
    git add "$GIT_CLIFF_OUTPUT"
}

function cliff_changelog_amend
{
    git commit --amend --no-edit
}

rule cliff_changelog_amend: cliff_changelog -

function cliff_changelog_commit
{
    git commit -m "CHORE: update $GIT_CLIFF_OUTPUT"
}

rule cliff_changelog_commit: cliff_changelog -

