#!/bash
# shellcheck disable=2016

## git cliff changelog generation

export GIT_CLIFF_OUTPUT="${GIT_CLIFF_OUTPUT:-CHANGELOG.md}"

function cliff_changelog
{
    git cliff "$@"
    [[ -f "cliff.toml" ]] && git add "cliff.toml"
    git add "$GIT_CLIFF_OUTPUT"
}

rule cliff_changelog_amend: 'cliff_changelog -- "$(git rev-list --max-parents=0 HEAD)"..HEAD~1' -- '
     git commit --amend --no-edit
'

rule cliff_changelog_commit: cliff_changelog -- '
     git commit -m "CHORE: update $GIT_CLIFF_OUTPUT"
'

