#!/bash
# shellcheck disable=2016

### Bash completion support for bar

## Completion API - called by contrib/bar_complete
## Usage: bar complete <word> <prev>
rule complete: -- '\
    # Simple completion - just list all rules
    local rule
    for rule in "${!BAR_RULES[@]}"; do
        echo "$rule"
    done | head -50
'
