#!/bash
# shellcheck disable=2016

### Bash completion support for bar
###
### This module provides a 'complete' rule that can be used to generate completions programmatically.
### However, for bash completion, the contrib/bar_complete script is used instead because it:
###   1. Parses files directly without loading bar (much faster)
###   2. Doesn't trigger SETUP/CLEANUP rules
###   3. Works independently of the current Barf file
###
### The completion script finds:
###   - User rule files in current directory (files with 'function'/'rule' or shebang pointing to bar/please)
###   - All rules and functions defined in Barf/Pleasef and Bar.d/ modules
###
### Installation is automatic when running 'bar init_install' - it creates a symlink:
###   ~/.bash_completion.d/bar_complete -> <bar_repo>/contrib/bar_complete

## Programmatic completion API - lists all available rules
## This can be called from scripts but is not used by bash completion
rule complete: -- '\
    # List all rules
    local rule
    for rule in "${!BAR_RULES[@]}"; do
        echo "$rule"
    done | head -50
'
