#!/bash
# shellcheck disable=2016

function git_is_clean ## - Checks if there are modified files, fails if there are any.
{
    if git diff --exit-code; then
        debug "nothing modified"
        return 0
    else
        info "files got modified"
        return 1
    fi
}

rule git_is_clean: is_git_repository -

function git_branch_matches ## [branchpattern..] - Checks that the current git branch matches any of the patterns
{
    # shellcheck disable=SC2155
    local branch=$(git_branch_name)
    for pat in "$@"; do
        [[ "$branch" =~ $pat ]] && {
            debug "$branch matches $pat"
            return 0
        }
    done
    trace "$branch does not match $*"
    return 1
}

rule git_branch_matches: is_git_repository -

# A set of common branch matchers
rule is_git_main_branch: 'git_branch_matches main master'
rule is_git_release_branch: 'git_branch_matches release-* release/*'
rule is_git_devel_branch: 'git_branch_matches devel-* devel/*'
rule is_git_feature_branch: 'git_branch_matches feature-* feature/*'
rule is_git_bugfix_branch: 'git_branch_matches bugfix-* bugfix/* fix-* fix/*'
rule is_git_hotfix_branch: 'git_branch_matches hotfix-* hotfix/*'
rule is_git_improvment_branch: 'git_branch_matches improvement-* improvement/*'
rule is_git_doc_branch: 'git_branch_matches doc-* doc/*'
rule is_git_wip_branch: 'git_branch_matches wip-* wip/*'
rule is_git_experimental_branch: 'git_branch_matches experiment-* experiment/*'
