#!/bash
# shellcheck disable=2016

function git_is_clean ## - Checks if there are modified files, fails if there are any.
{
    if git diff --exit-code; then
        debug "nothing modified"
        return 0
    else
        info "files got modified"
        return 1
    fi
}

rule git_is_clean: is_git_repository -

function git_branch_matches ## [branchpattern..] - Checks that the current git branch matches any of the patterns
{
    # shellcheck disable=SC2155
    local branch=$(git_branch_name)
    for pat in "$@"; do
        [[ "$branch" =~ $pat ]] && {
            debug "$branch matches $pat"
            return 0
        }
    done
    trace "$branch does not match $*"
    return 1
}

rule git_branch_matches: is_git_repository -

# A set of git hook matchers
rule is_git_pre_commit_hook: 'called_as pre-commit'
rule is_git_pre_merge_commit_hook: 'called_as pre-merge-commit'
rule is_git_prepare_commit_msg_hook: 'called_as prepare-commit-msg'
rule is_git_commit_msg_hook: 'called_as commit-msg'
rule is_git_applypatch_msg_hook: 'called_as applypatch-msg'
rule is_git_pre_applypatch_hook: 'called_as pre-applypatch'
rule is_git_post_applypatch_hook: 'called_as post-applypatch'
rule is_git_post_commit_hook: 'called_as post-commit'
rule is_git_pre_rebase_hook: 'called_as pre-rebase'
rule is_git_post_checkout_hook: 'called_as post-checkout'
rule is_git_post_merge_hook: 'called_as post-merge'
rule is_git_pre_push_hook: 'called_as pre-push'
rule is_git_pre_receive_hook: 'called_as pre-receive'
rule is_git_update_hook: 'called_as update'
rule is_git_proc_receive_hook: 'called_as proc-receive'
rule is_git_post_receive_hook: 'called_as post-receive'
rule is_git_post_update_hook: 'called_as post-update'
rule is_git_reference_transaction_hook: 'called_as reference-transaction'
rule is_git_push_to_checkout_hook: 'called_as push-to-checkout'
rule is_git_pre_auto_gc_hook: 'called_as pre-auto-gc'
rule is_git_post_rewrite_hook: 'called_as post-rewrite'
rule is_git_sendemail_validate_hook: 'called_as sendemail-validate'
rule is_git_fsmonitor_watchman_hook: 'called_as fsmonitor-watchman'
rule is_git_post_index_change_hook: 'called_as post-index-change'

# A set of common branch matchers
rule is_git_main_branch: 'git_branch_matches main master'
rule is_git_release_branch: 'git_branch_matches release-* release/*'
rule is_git_devel_branch: 'git_branch_matches devel-* devel/*'
rule is_git_feature_branch: 'git_branch_matches feature-* feature/*'
rule is_git_bugfix_branch: 'git_branch_matches bugfix-* bugfix/* fix-* fix/*'
rule is_git_hotfix_branch: 'git_branch_matches hotfix-* hotfix/*'
rule is_git_improvement_branch: 'git_branch_matches improvement-* improvement/*'
rule is_git_doc_branch: 'git_branch_matches doc-* doc/*'
rule is_git_wip_branch: 'git_branch_matches wip-* wip/*'
rule is_git_experimental_branch: 'git_branch_matches experiment-* experiment/*'
