#!/bash
#shellcheck disable=2016

# for now only ripgrep support, feel free to PR other searchers

function search_for
{
    rg -S -p "$@" | less -SR
}

rule search_for: 'is_command_installed less' 'is_command_installed rg' -

rule search_issues: -- search_for -B1 -A2 '" (FIXME|TODO|PLANNED): "'
rule search_fixmes: -- search_for " FIXME: "
rule search_todos: -- search_for " TODO: "
rule search_planned: -- search_for " PLANNED: "
