#!/bash

rule is_shellcheck_available: 'is_command_installed shellcheck' has_shellcheck_scripts

function shellcheck_is_shscript ## <file> - Check if <file> is a shell script
{
    [[ -f "$1" ]] && { head -1 "$1" | grep -q "^#!.*sh" ; }
}

function has_shellcheck_shscripts ## - Checks whenever any shell scripts are versioned in git
{
    local file
    for file in $(git_ls_files --other); do
        if shellcheck_is_shscript "$file"; then
            trace "Shell scripts found"
            return 0
        fi
    done
    debug "No shell scripts found in the repository"
    return 1
}

# we will use git to list files
rule has_shellcheck_shscripts: is_git_toplevel -


function shellcheck_list_shscripts ## - List all shell scripts under git control
{
    local file
    for file in $(git_ls_files --other); do
        if shellcheck_is_shscript "$file"; then
            echo "$file"
        fi
    done
}

memofn shellcheck_list_shscripts

function shellcheck_lint ## - Test if all shell scripts under git control pass the linter.
{
    trace "shellcheck --color $(shellcheck_list_shscripts)"
    # shellcheck disable=SC2046
    shellcheck --color $(shellcheck_list_shscripts)
}

rule shellcheck_lint: has_shellcheck_shscripts? -

