#!/bash

### Support for the shellcheck shell linter.
###
### Beware: Shellcheck is surprisingly slow.

function shellcheck_list_shscripts ## List all shell scripts under git control
{
    local file
    for file in $(git_ls_files --other); do
        if shellcheck_is_shscript "$file"; then
            echo "$file"
        fi
    done
}

memofn shellcheck_list_shscripts

function shellcheck_lint ## Test if all shell scripts under git control pass the linter.
{
    trace "shellcheck --color $(shellcheck_list_shscripts)"
    # shellcheck disable=SC2046
    shellcheck --color $(shellcheck_list_shscripts)
}
