#!/bash
# shellcheck disable=2016,2086

### Continious supervision by a file watcher

## Run bar in a file watcher ('entr'), whenever a file
## changed it will be run again.
rule watch: --conclusive is_entr_installed? -- '
     require entr
     entr_watch "${RULE_ARGS[*]}"
'
rule watch: -- warn "no supported file watcher available"
